version: 2

jobs:
    build:
      machine: true
      resource_class: arm.medium
      steps:
        - checkout
        - run:
            name: Build My portfolio
            command: |
              docker build . -t busshi/portfolio
        - run:
            name: Push image to docker hub
            command: |
              echo "$DOCKERHUB_API_KEY" | docker login --username $DOCKERHUB_LOGIN --password-stdin
              docker push busshi/portfolio:latest

workflows:
    version: 2
    build:
      jobs:
        - build:
            filters:
              branches:
                only:
                - master
