name: build
on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: build and push to dockerhub
    steps:
      - name: Clone app
        uses: actions/checkout@v2
 
      - name: Build portfolio image
        run: |
          docker build . -t busshi/portfolio

      - name: Push image to Dockerhub
        run: |
          echo "$DOCKERHUB_API_KEY" | docker login --username $DOCKERHUB_LOGIN --password-stdin
          docker push busshi/portfolio:latest
        env:
          DOCKERHUB_API_KEY: ${{ secrets.DOCKERHUB_API_KEY }}
          DOCKERHUB_LOGIN: ${{ secrets.DOCKERHUB_LOGIN }}
